import { describe, expect, it } from "vitest";
import { BALANCE_STATEMENT_ROWS } from "@/lib/ivcee-balance-catalog";
import { VOCI, labelOf } from "@/lib/ivcee-catalog";
import {
  CE_A, CE_B, CE_C, CE_D, CE_E, CE_IMPOSTE,
  COUNTERPART_PICKER_LABELS,
  DEBT_GROUPS,
  RETTIFICHE_BS_ATTIVO, RETTIFICHE_BS_OTHER_PASSIVO, RETTIFICHE_BS_PN,
  RETTIFICHE_LABELS,
} from "@/lib/pratica-rettifiche-rules";
import {
  buildBalanceItemsWithTotals,
  buildIncomeItemsWithEbitda,
} from "@/lib/pratica-statement-rows";
import type { IntraYearComparisonItem } from "@/types/api";

/** Una riga di prospetto: il campo se c'è, altrimenti un marcatore stabile. */
const rowKey = (r: { field?: string; label: string }) => r.field ?? `computed:${r.label}`;

/** Ordine di resa di RettificheTab: attivo, PN, altri passivi, gruppi debiti, CE. */
const rettificheCodes = (): string[] => [
  ...RETTIFICHE_BS_ATTIVO,
  ...RETTIFICHE_BS_PN,
  ...RETTIFICHE_BS_OTHER_PASSIVO,
  ...DEBT_GROUPS.flatMap((g) => [...g.entro, ...g.oltre]),
  ...CE_A, ...CE_B, ...CE_C, ...CE_D, ...CE_E, ...CE_IMPOSTE,
];

const item = (code: string): IntraYearComparisonItem => ({
  code, label: code,
  partial_value: 1000, reference_value: 900, prior_value: 800,
  pct_of_reference: 0, annualized_value: 0,
});

/** Fixture: ogni codice che le viste possono ricevere dal server. */
const BS_FIXTURE = [
  "sp01_crediti_soci", "sp02_immob_immateriali", "sp03_immob_materiali",
  "sp04_immob_finanziarie", "sp05_rimanenze", "sp06_crediti_breve",
  "sp07_crediti_lungo", "sp08_attivita_finanziarie", "sp09_disponibilita_liquide",
  "sp10_ratei_risconti_attivi", "sp11_capitale", "sp12_riserve",
  "sp13_utile_perdita", "sp14_fondi_rischi", "sp15_tfr",
  "sp16_debiti_breve", "sp17_debiti_lungo", "sp18_ratei_risconti_passivi",
].map(item);

const CE_FIXTURE = [
  "ce01_ricavi_vendite", "ce02_variazioni_rimanenze", "ce03_lavori_interni",
  "ce04_altri_ricavi", "ce05_materie_prime", "ce06_servizi", "ce07_godimento_beni",
  "ce08_costi_personale", "ce09_ammortamenti", "ce10_var_rimanenze_mat_prime",
  "ce11_accantonamenti", "ce12_oneri_diversi", "ce13_proventi_partecipazioni",
  "ce14_altri_proventi_finanziari", "ce15_oneri_finanziari", "ce16_utili_perdite_cambi",
  "ce17_rettifiche_attivita_fin", "ce18_proventi_straordinari",
  "ce19_oneri_straordinari", "ce20_imposte",
].map(item);

// Generato al Task 1 dallo stato pre-refactoring. Questi elenchi NON vanno
// aggiornati per far passare un test: se cambiano, una vista ha perso o
// riordinato una riga, ed è quello il difetto.
const ATTESI_BALANCE: string[] = [
  "computed:ATTIVO",
  "sp01_crediti_soci",
  "computed:B) IMMOBILIZZAZIONI",
  "sp02_immob_immateriali",
  "sp03_immob_materiali",
  "sp04_immob_finanziarie",
  "sp04a_partecipazioni",
  "sp04b_crediti_immob_breve",
  "sp04c_crediti_immob_lungo",
  "computed:Totale crediti immobilizzati",
  "sp04d_altri_titoli",
  "sp04e_strumenti_derivati_attivi",
  "fixed_assets",
  "computed:C) ATTIVO CIRCOLANTE",
  "sp05_rimanenze",
  "sp05a_materie_prime",
  "sp05b_prodotti_in_corso",
  "sp05c_lavori_in_corso",
  "sp05d_prodotti_finiti",
  "sp05e_acconti",
  "sp06_crediti_breve",
  "sp06a_crediti_clienti_breve",
  "sp06b_crediti_controllate_breve",
  "sp06c_crediti_collegate_breve",
  "sp06d_crediti_controllanti_breve",
  "sp06e_crediti_tributari_breve",
  "sp06f_imposte_anticipate_breve",
  "sp06g_crediti_altri_breve",
  "sp07_crediti_lungo",
  "sp07a_crediti_clienti_lungo",
  "sp07b_crediti_controllate_lungo",
  "sp07c_crediti_collegate_lungo",
  "sp07d_crediti_controllanti_lungo",
  "sp07e_crediti_tributari_lungo",
  "sp07f_imposte_anticipate_lungo",
  "sp07g_crediti_altri_lungo",
  "sp08_attivita_finanziarie",
  "sp09_disponibilita_liquide",
  "current_assets",
  "sp10_ratei_risconti_attivi",
  "total_assets",
  "computed:PASSIVO E PATRIMONIO NETTO",
  "computed:A) PATRIMONIO NETTO",
  "sp11_capitale",
  "sp12a_riserva_sovrapprezzo",
  "sp12b_riserve_rivalutazione",
  "sp12c_riserva_legale",
  "sp12d_riserve_statutarie",
  "sp12e_altre_riserve",
  "sp12f_riserva_copertura_flussi",
  "sp12g_utili_perdite_portati",
  "sp12h_riserva_neg_azioni_proprie",
  "sp13_utile_perdita",
  "computed:Totale patrimonio netto",
  "sp14_fondi_rischi",
  "sp14a_fondi_trattamento_quiescenza",
  "sp14b_fondi_imposte",
  "sp14c_strumenti_derivati_passivi",
  "sp14d_altri_fondi",
  "sp15_tfr",
  "computed:D) DEBITI",
  "computed:Banche",
  "sp16a_debiti_banche_breve",
  "sp17a_debiti_banche_lungo",
  "computed:Altri finanziatori",
  "sp16b_debiti_altri_finanz_breve",
  "sp17b_debiti_altri_finanz_lungo",
  "computed:Obbligazioni",
  "sp16c_debiti_obbligazioni_breve",
  "sp17c_debiti_obbligazioni_lungo",
  "computed:Fornitori",
  "sp16d_debiti_fornitori_breve",
  "sp17d_debiti_fornitori_lungo",
  "computed:Debiti tributari",
  "sp16e_debiti_tributari_breve",
  "sp17e_debiti_tributari_lungo",
  "computed:Debiti previdenziali",
  "sp16f_debiti_previdenza_breve",
  "sp17f_debiti_previdenza_lungo",
  "computed:Altri debiti",
  "sp16g_altri_debiti_breve",
  "sp17g_altri_debiti_lungo",
  "computed:Totale debiti",
  "sp18_ratei_risconti_passivi",
  "computed:TOTALE PASSIVO E PATRIMONIO NETTO",
  "computed:DIFFERENZA (Attivo - Passivo)",
];
const ATTESI_RETTIFICHE: string[] = [
  "sp01_crediti_soci",
  "sp02_immob_immateriali",
  "sp03_immob_materiali",
  "sp04_immob_finanziarie",
  "sp04a_partecipazioni",
  "sp04b_crediti_immob_breve",
  "sp04c_crediti_immob_lungo",
  "sp04d_altri_titoli",
  "sp04e_strumenti_derivati_attivi",
  "sp05_rimanenze",
  "sp05a_materie_prime",
  "sp05b_prodotti_in_corso",
  "sp05c_lavori_in_corso",
  "sp05d_prodotti_finiti",
  "sp05e_acconti",
  "sp06_crediti_breve",
  "sp06a_crediti_clienti_breve",
  "sp06b_crediti_controllate_breve",
  "sp06c_crediti_collegate_breve",
  "sp06d_crediti_controllanti_breve",
  "sp06e_crediti_tributari_breve",
  "sp06f_imposte_anticipate_breve",
  "sp06g_crediti_altri_breve",
  "sp07_crediti_lungo",
  "sp07a_crediti_clienti_lungo",
  "sp07b_crediti_controllate_lungo",
  "sp07c_crediti_collegate_lungo",
  "sp07d_crediti_controllanti_lungo",
  "sp07e_crediti_tributari_lungo",
  "sp07f_imposte_anticipate_lungo",
  "sp07g_crediti_altri_lungo",
  "sp08_attivita_finanziarie",
  "sp09_disponibilita_liquide",
  "sp10_ratei_risconti_attivi",
  "sp11_capitale",
  "sp12a_riserva_sovrapprezzo",
  "sp12b_riserve_rivalutazione",
  "sp12c_riserva_legale",
  "sp12d_riserve_statutarie",
  "sp12e_altre_riserve",
  "sp12f_riserva_copertura_flussi",
  "sp12g_utili_perdite_portati",
  "sp13_utile_perdita",
  "sp12h_riserva_neg_azioni_proprie",
  "sp14_fondi_rischi",
  "sp15_tfr",
  "sp16a_debiti_banche_breve",
  "sp17a_debiti_banche_lungo",
  "sp16b_debiti_altri_finanz_breve",
  "sp17b_debiti_altri_finanz_lungo",
  "sp16c_debiti_obbligazioni_breve",
  "sp17c_debiti_obbligazioni_lungo",
  "sp16d_debiti_fornitori_breve",
  "sp17d_debiti_fornitori_lungo",
  "sp16e_debiti_tributari_breve",
  "sp17e_debiti_tributari_lungo",
  "sp16f_debiti_previdenza_breve",
  "sp17f_debiti_previdenza_lungo",
  "sp16g_altri_debiti_breve",
  "sp17g_altri_debiti_lungo",
  "ce01_ricavi_vendite",
  "ce02_variazioni_rimanenze",
  "ce03_lavori_interni",
  "ce04_altri_ricavi",
  "ce05_materie_prime",
  "ce06_servizi",
  "ce07_godimento_beni",
  "ce08_costi_personale",
  "ce08b_salari_stipendi",
  "ce08c_oneri_sociali",
  "ce08a_tfr_accrual",
  "ce08d_altri_costi_personale",
  "ce09_ammortamenti",
  "ce09a_ammort_immateriali",
  "ce09b_ammort_materiali",
  "ce09c_svalutazioni",
  "ce09d_svalutazione_crediti",
  "ce10_var_rimanenze_mat_prime",
  "ce11_accantonamenti",
  "ce11b_altri_accantonamenti",
  "ce12_oneri_diversi",
  "ce13_proventi_partecipazioni",
  "ce14_altri_proventi_finanziari",
  "ce15_oneri_finanziari",
  "ce16_utili_perdite_cambi",
  "ce17a_rivalutazioni",
  "ce17b_svalutazioni",
  "ce17_rettifiche_attivita_fin",
  "ce18_proventi_straordinari",
  "ce19_oneri_straordinari",
  "ce20_imposte",
];
const ATTESI_CONFRONTO_BS: string[] = [
  "_hdr_attivo",
  "sp01_crediti_soci",
  "_hdr_immob",
  "sp02_immob_immateriali",
  "sp03_immob_materiali",
  "sp04_immob_finanziarie",
  "sp04a_partecipazioni",
  "sp04b_crediti_immob_breve",
  "sp04c_crediti_immob_lungo",
  "sp04d_altri_titoli",
  "sp04e_strumenti_derivati_attivi",
  "_totale_immob",
  "_hdr_circ",
  "sp05_rimanenze",
  "sp06_crediti_breve",
  "sp06a_crediti_clienti_breve",
  "sp06b_crediti_controllate_breve",
  "sp06c_crediti_collegate_breve",
  "sp06d_crediti_controllanti_breve",
  "sp06e_crediti_tributari_breve",
  "sp06f_imposte_anticipate_breve",
  "sp06g_crediti_altri_breve",
  "sp07_crediti_lungo",
  "sp07a_crediti_clienti_lungo",
  "sp07b_crediti_controllate_lungo",
  "sp07c_crediti_collegate_lungo",
  "sp07d_crediti_controllanti_lungo",
  "sp07e_crediti_tributari_lungo",
  "sp07f_imposte_anticipate_lungo",
  "sp07g_crediti_altri_lungo",
  "sp08_attivita_finanziarie",
  "sp09_disponibilita_liquide",
  "_totale_circ",
  "sp10_ratei_risconti_attivi",
  "_totale_attivo",
  "_hdr_passivo",
  "_hdr_pn",
  "sp11_capitale",
  "sp12a_riserva_sovrapprezzo",
  "sp12b_riserve_rivalutazione",
  "sp12c_riserva_legale",
  "sp12d_riserve_statutarie",
  "sp12e_altre_riserve",
  "sp12f_riserva_copertura_flussi",
  "sp12g_utili_perdite_portati",
  "sp13_utile_perdita",
  "sp12h_riserva_neg_azioni_proprie",
  "_totale_pn",
  "sp14_fondi_rischi",
  "sp15_tfr",
  "_hdr_debiti",
  "_debt_banche",
  "sp16a_debiti_banche_breve",
  "sp17a_debiti_banche_lungo",
  "_debt_altri_finanz",
  "sp16b_debiti_altri_finanz_breve",
  "sp17b_debiti_altri_finanz_lungo",
  "_debt_obbligazioni",
  "sp16c_debiti_obbligazioni_breve",
  "sp17c_debiti_obbligazioni_lungo",
  "_debt_fornitori",
  "sp16d_debiti_fornitori_breve",
  "sp17d_debiti_fornitori_lungo",
  "_debt_tributari",
  "sp16e_debiti_tributari_breve",
  "sp17e_debiti_tributari_lungo",
  "_debt_previdenza",
  "sp16f_debiti_previdenza_breve",
  "sp17f_debiti_previdenza_lungo",
  "_debt_altri",
  "sp16g_altri_debiti_breve",
  "sp17g_altri_debiti_lungo",
  "_totale_debiti",
  "sp18_ratei_risconti_passivi",
  "_totale_passivo",
  "_differenza",
];
const ATTESI_CONFRONTO_CE: string[] = [
  "_hdr_a",
  "ce01_ricavi_vendite",
  "ce02_variazioni_rimanenze",
  "ce03_lavori_interni",
  "ce04_altri_ricavi",
  "_totale_vp",
  "_hdr_b",
  "ce05_materie_prime",
  "ce06_servizi",
  "ce07_godimento_beni",
  "ce08_costi_personale",
  "ce08b_salari_stipendi",
  "ce08c_oneri_sociali",
  "ce08a_tfr_accrual",
  "ce08d_altri_costi_personale",
  "ce09_ammortamenti",
  "ce09a_ammort_immateriali",
  "ce09b_ammort_materiali",
  "ce09c_svalutazioni",
  "ce09d_svalutazione_crediti",
  "ce10_var_rimanenze_mat_prime",
  "ce11_accantonamenti",
  "ce11b_altri_accantonamenti",
  "ce12_oneri_diversi",
  "_totale_cp",
  "_ebitda",
  "_ebit",
  "_hdr_c",
  "ce13_proventi_partecipazioni",
  "ce14_altri_proventi_finanziari",
  "ce15_oneri_finanziari",
  "ce16_utili_perdite_cambi",
  "_totale_fin",
  "_hdr_d",
  "ce17a_rivalutazioni",
  "ce17b_svalutazioni",
  "ce17_rettifiche_attivita_fin",
  "_hdr_e",
  "ce18_proventi_straordinari",
  "ce19_oneri_straordinari",
  "_totale_straord",
  "_profit_before_tax",
  "ce20_imposte",
  "_net_profit",
];

describe("invariante: nessuna vista perde o riordina righe", () => {
  it("prospetto SP (forecast/balance e report-appendices)", () => {
    expect(BALANCE_STATEMENT_ROWS.map(rowKey)).toEqual(ATTESI_BALANCE);
  });

  it("Rettifiche: ordine di resa completo", () => {
    expect(rettificheCodes()).toEqual(ATTESI_RETTIFICHE);
  });

  it("Confronto: righe SP costruite dal server", () => {
    expect(buildBalanceItemsWithTotals(BS_FIXTURE).map((i) => i.code)).toEqual(ATTESI_CONFRONTO_BS);
  });

  it("Confronto: righe CE costruite dal server", () => {
    expect(buildIncomeItemsWithEbitda(CE_FIXTURE, 9).map((i) => i.code)).toEqual(ATTESI_CONFRONTO_CE);
  });
});

describe("cross-check: il catalogo riproduce la regola delle etichette", () => {
  it("ogni codice etichettato dalle fonti vecchie esiste nel catalogo", () => {
    const known = new Set(VOCI.map((v) => v.code));
    const mancanti = Object.keys(RETTIFICHE_LABELS).filter((c) => !known.has(c));
    expect(mancanti).toEqual([]);
  });

  it("i sotto-conti coperti dal selettore usano il suo testo come etichetta autonoma", () => {
    for (const [code, atteso] of Object.entries(COUNTERPART_PICKER_LABELS)) {
      expect(labelOf(code)).toBe(atteso);
    }
  });

  it("nessuna etichetta del catalogo conserva i rientri delle fonti vecchie", () => {
    const conRientro = VOCI.filter((v) => v.label.startsWith(" "));
    expect(conRientro.map((v) => v.code)).toEqual([]);
  });
});
